### ISSUE TITLE
error on pfsense 2.1.5-RELEASE (i386) 

### ISSUE THREAD

**Issue by fcaeiro** [alexpmorris/pfsense-status-gateways-json#1]
Hi i got this error 
"Fatal error: Cannot redeclare return_apinger_defaults() (previously declared in /etc/inc/gwlb.inc:37) in /etc/inc/gwlb.inc on line 43"

thanks

**Comment by alexpmorris** [comment]
seems like require('gwlb.inc') was already declared in interfaces.inc - and perhaps latest pfsense is complaining about it versus older version that overlooked it (different php settings).  I commented the line out:

##require("gwlb.inc");  <-- already declared in interfaces.inc

and it still worked for me as well, so hopefully that should do it.
