### ISSUE TITLE
interface name incorrect

### ISSUE THREAD

**Issue by ffes** [alexpmorris/pfsense-status-gateways-json#2]
There is a `substr()` at line 78 to cut off the first three characters of the interface name.

```php
$iface = substr(strtolower($a_gateway['name']),3);
```

This results in two empty interfaces on our system.

Any reason to have this in the code, other then your personal needs? And if so, it would be nice if it was documented in the README.

**Comment by alexpmorris** [comment]
on my systems all the interface names are preceded by "gw_", which I removed to clean it up.  Didn't realize it was adjustable, as appears to be the case in your configuration.  You should be able to correct it with the following two lines (or even just the first line):

  $iface = strtolower($a_gateway['name']);
  if (substr($iface,0,3) == "gw_") $iface = substr($iface,3);

**Comment by ffes** [comment]
I already had changed it on my server. I even deleted the `strtolower()`

But thanks for fixing it in df8517d34e436444e0234da31752e4e40e58d2ab
